-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ESTOQUEREGISTRO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ESTOQUEREGISTRO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ESTOQUEREGISTRO` DEFAULT CHARACTER SET utf8 ;
USE `ESTOQUEREGISTRO` ;

-- -----------------------------------------------------
-- Table `ESTOQUEREGISTRO`.`ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ESTOQUEREGISTRO`.`ESTOQUE` (
  `ID_ESTOQUE` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `MODELO` VARCHAR(45) NOT NULL,
  `FOTO` VARCHAR(100) NULL,
  `DESCRICAO` VARCHAR(200) NULL,
  `COD_FABRICANTE` VARCHAR(45) NULL,
  `QUANT_ATUAL` INT NOT NULL,
  `QUANT_MIN` INT NOT NULL,
  `MARCA` VARCHAR(45) NULL,
  `DATE_REGISTER` DATETIME NOT NULL,
  `POSICAO_PRATELEIRA` VARCHAR(45) NOT NULL,
  `SETOR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ESTOQUE`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
