/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.estoque.telas;

import br.com.estoque.dao.EstoqueDao;
import br.com.estoque.factory.ConnectionFactory;
import br.com.estoque.model.Estoque;
import static java.lang.Boolean.FALSE;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author rafae
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    
    EstoqueDao listar = new EstoqueDao();
    
    private int index;
    
    public TelaCadastro() throws Exception {
        initComponents();
        carregarTabela();
        desabilitaBotao();
        desabilitaCampText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome_Label = new javax.swing.JLabel();
        modelo_Label = new javax.swing.JLabel();
        foto_Label = new javax.swing.JLabel();
        descricao_Label = new javax.swing.JLabel();
        quant_atual_Label = new javax.swing.JLabel();
        cod_fabricante_Label = new javax.swing.JLabel();
        quant_min_Label = new javax.swing.JLabel();
        marca_Label = new javax.swing.JLabel();
        posicao_prateleira_Label = new javax.swing.JLabel();
        setor_Label = new javax.swing.JLabel();
        modelo_TextField = new javax.swing.JTextField();
        nome_TextField = new javax.swing.JTextField();
        marca_TextField = new javax.swing.JTextField();
        posicao_prateleira_TextField = new javax.swing.JTextField();
        cod_fabricante_TextField = new javax.swing.JTextField();
        quant_min_TextField = new javax.swing.JTextField();
        quant_atual_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao_TextArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEstoque = new javax.swing.JTable();
        novo = new javax.swing.JButton();
        primeiro = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        avancar = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        id_estoque_Label = new javax.swing.JLabel();
        id_estoque_TextField = new javax.swing.JTextField();
        date_register_Label = new javax.swing.JLabel();
        date_register_TextField = new javax.swing.JTextField();
        setor_TextField = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calypto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de almoxarifado"));
        jPanel1.setAutoscrolls(true);

        nome_Label.setText("Nome");

        modelo_Label.setText("Modelo");

        foto_Label.setText("Foto");

        descricao_Label.setText("Descrição");

        quant_atual_Label.setText("Quantidade atual");

        cod_fabricante_Label.setText("Código do fabricante");

        quant_min_Label.setText("Quantidade mínima");

        marca_Label.setText("Marca");

        posicao_prateleira_Label.setText("Prateleira");

        setor_Label.setText("Setor");

        modelo_TextField.setBorder(null);

        nome_TextField.setBorder(null);
        nome_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_TextFieldActionPerformed(evt);
            }
        });

        marca_TextField.setBorder(null);

        posicao_prateleira_TextField.setBorder(null);
        posicao_prateleira_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicao_prateleira_TextFieldActionPerformed(evt);
            }
        });

        cod_fabricante_TextField.setBorder(null);

        quant_min_TextField.setBorder(null);
        quant_min_TextField.setName(""); // NOI18N
        quant_min_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quant_min_TextFieldActionPerformed(evt);
            }
        });

        quant_atual_TextField.setBorder(null);

        descricao_TextArea.setColumns(20);
        descricao_TextArea.setRows(5);
        jScrollPane1.setViewportView(descricao_TextArea);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tabelaEstoque.setAutoCreateRowSorter(true);
        tabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "MODELO", "MARCA", "SETOR", "PRATELEIRA", "QUANTIDADE ATUAL", "QUANTIDADE MÍNIMA", "CÓDIGO DO FABRICANTE", "DATA DO REGISTRO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEstoque.setShowGrid(true);
        tabelaEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEstoqueMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaEstoque);

        novo.setText("NOVO");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        primeiro.setText("PRIMEIRO");
        primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroActionPerformed(evt);
            }
        });

        btGravar.setText("GRAVAR");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btAlterar.setText("ALTERAR");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        avancar.setText("AVANÇAR");
        avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarActionPerformed(evt);
            }
        });

        ultimo.setText("ÚLTIMO");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        id_estoque_Label.setText("ID");

        id_estoque_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_estoque_TextFieldActionPerformed(evt);
            }
        });

        date_register_Label.setText("DATA");

        setor_TextField.setBorder(null);

        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(posicao_prateleira_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(posicao_prateleira_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(marca_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nome_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(modelo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nome_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                            .addComponent(modelo_TextField)
                                            .addComponent(marca_TextField))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cod_fabricante_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(quant_min_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(quant_atual_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(setor_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quant_min_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cod_fabricante_TextField)
                                            .addComponent(quant_atual_TextField)
                                            .addComponent(setor_TextField)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addComponent(id_estoque_Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(id_estoque_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btGravar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btAlterar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(primeiro)
                                        .addGap(12, 12, 12)
                                        .addComponent(ultimo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(avancar)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(voltar)
                                    .addComponent(btExcluir))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(date_register_Label)
                                .addGap(18, 18, 18)
                                .addComponent(date_register_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(descricao_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(189, 189, 189)
                                .addComponent(foto_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(704, 704, 704))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome_Label)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nome_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(modelo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(modelo_Label))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(marca_Label)
                                    .addComponent(marca_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(posicao_prateleira_Label)
                                    .addComponent(posicao_prateleira_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novo)
                            .addComponent(btGravar)
                            .addComponent(btAlterar)
                            .addComponent(btExcluir)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod_fabricante_Label)
                            .addComponent(cod_fabricante_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricao_Label)
                            .addComponent(foto_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quant_min_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quant_min_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(quant_atual_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quant_atual_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setor_Label)
                                    .addComponent(setor_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(date_register_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_register_Label)
                                    .addComponent(id_estoque_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_estoque_Label))))))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(avancar)
                    .addComponent(primeiro)
                    .addComponent(ultimo))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void posicao_prateleira_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicao_prateleira_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicao_prateleira_TextFieldActionPerformed

    private void nome_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_TextFieldActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
        habilitaCampText();
        habilitaBotao();
        limparTexto();
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
    }//GEN-LAST:event_novoActionPerformed

    private void primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroActionPerformed
        // TODO add your handling code here:
        index = 0;
        setarCampos(listar.getEstoqueRegistro().get(index));
        
    }//GEN-LAST:event_primeiroActionPerformed

    private void avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarActionPerformed
        // TODO add your handling code here:
        index++;
        if(index<tabelaEstoque.getRowCount())
        {
            setarCampos(listar.getEstoqueRegistro().get(index));
        }
        else
        {
            index = (tabelaEstoque.getRowCount()-1);
            setarCampos(listar.getEstoqueRegistro().get(index));
            JOptionPane.showMessageDialog(null, "Você já esta no último registro","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_avancarActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        Estoque stq = new Estoque();
        EstoqueDao stqDao = new EstoqueDao();
        
        stq.setNome(nome_TextField.getText());
        stq.setModelo(modelo_TextField.getText());
        stq.setMarca(marca_TextField.getText());
        stq.setPosicao_prateleira(posicao_prateleira_TextField.getText());
        stq.setDescricao(descricao_TextArea.getText());
        stq.setCod_fabricante(cod_fabricante_TextField.getText());
        stq.setQuant_min(Integer.parseInt(quant_min_TextField.getText()));
        stq.setQuant_atual(Integer.parseInt(quant_atual_TextField.getText()));
        stq.setSetor(setor_TextField.getText());
        stq.setDescricao(descricao_TextArea.getText());
        stq.setDate_register(new Date());
        
        limparTexto();
        stqDao.save(stq);
        limparTexto();
        try {
            carregarTabela();
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btGravarActionPerformed
    
    private void setarCampos(Estoque estoque)
    {
        id_estoque_TextField.setText(String.valueOf(estoque.getId_estoque()));
        nome_TextField.setText(estoque.getNome());
        modelo_TextField.setText(estoque.getModelo());
        marca_TextField.setText(estoque.getMarca());
        posicao_prateleira_TextField.setText(estoque.getPosicao_prateleira());
        cod_fabricante_TextField.setText(estoque.getCod_fabricante());
        quant_atual_TextField.setText(String.valueOf(estoque.getQuant_atual()));
        quant_min_TextField.setText(String.valueOf(estoque.getQuant_min()));
        setor_TextField.setText(estoque.getSetor());
        descricao_TextArea.setText(estoque.getDescricao());
        date_register_TextField.setText(String.valueOf(estoque.getDate_register()));        
    }
    
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        
        Estoque stq = new Estoque();
        EstoqueDao stqDao = new EstoqueDao();
        
        int index = tabelaEstoque.getSelectedRow();
        
        stq = stqDao.getEstoqueRegistro().get(index);
        
        switch(JOptionPane.showConfirmDialog(null, "Deseja excluir o item de código: \n"+
                stq.getId_estoque()+"\n"+
                "Nome: "+stq.getNome(),
                "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE))
        {
            case 0:
                stqDao.deleteByID(stq);

                try {
                    carregarTabela();
                } catch (Exception error) {
                    JOptionPane.showMessageDialog(null, "Erro ao exluir "+error,"ERRO",HEIGHT);
                }
                
                break;

            case 1:
                JOptionPane.showMessageDialog(null, "Nenhuma exclusão foi feita","AVISO.",JOptionPane.INFORMATION_MESSAGE);
                
                break;
        }
    }//GEN-LAST:event_btExcluirActionPerformed
    
    private void limparTexto()
    {
        nome_TextField.setText("");
        modelo_TextField.setText("");
        marca_TextField.setText("");
        posicao_prateleira_TextField.setText("");
        cod_fabricante_TextField.setText("");
        quant_atual_TextField.setText("");
        quant_min_TextField.setText("");
        cod_fabricante_TextField.setText("");
        date_register_TextField.setText("");
        id_estoque_TextField.setText("");
        descricao_TextArea.setText("");
        setor_TextField.setText("");
    }
    
    private void desabilitaBotao()
    {
        btGravar.setEnabled(false);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
    }
    private void desabilitaCampText()
    {
        nome_TextField.setEnabled(false);
        modelo_TextField.setEnabled(false);
        marca_TextField.setEnabled(false);
        posicao_prateleira_TextField.setEnabled(false);
        cod_fabricante_TextField.setEnabled(false);
        quant_atual_TextField.setEnabled(false);
        quant_min_TextField.setEnabled(false);
        cod_fabricante_TextField.setEnabled(false);
        date_register_TextField.setEnabled(false);
        id_estoque_TextField.setEnabled(false);
        descricao_TextArea.setEnabled(false);
        setor_TextField.setEditable(false);
    }
     private void habilitaBotao()
    {
        btGravar.setEnabled(true);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
    }
    private void habilitaCampText()
    {
        nome_TextField.setEnabled(true);
        modelo_TextField.setEnabled(true);
        marca_TextField.setEnabled(true);
        posicao_prateleira_TextField.setEnabled(true);
        cod_fabricante_TextField.setEnabled(true);
        quant_atual_TextField.setEnabled(true);
        quant_min_TextField.setEnabled(true);
        cod_fabricante_TextField.setEnabled(true);
        date_register_TextField.setEnabled(false);
        id_estoque_TextField.setEnabled(false);
        descricao_TextArea.setEnabled(true);
        setor_TextField.setEditable(true);
    }
    
    private void id_estoque_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_estoque_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_estoque_TextFieldActionPerformed

    private void quant_min_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quant_min_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quant_min_TextFieldActionPerformed

    private void tabelaEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEstoqueMouseClicked
        
        Estoque stq = new Estoque();
        EstoqueDao stqDao = new EstoqueDao();
        
        int index = tabelaEstoque.getSelectedRow();
        
        stq = stqDao.getEstoqueRegistro().get(index);
        
        //Seta as informações no campo de texto quando clica no item da tabela
        id_estoque_TextField.setText(String.valueOf(stq.getId_estoque()));
        nome_TextField.setText(stq.getNome());
        modelo_TextField.setText(stq.getModelo());
        marca_TextField.setText(stq.getModelo());
        setor_TextField.setText(stq.getSetor());
        posicao_prateleira_TextField.setText(stq.getPosicao_prateleira());
        quant_atual_TextField.setText(String.valueOf(stq.getQuant_atual()));
        quant_min_TextField.setText(String.valueOf(stq.getQuant_min()));
        cod_fabricante_TextField.setText(stq.getCod_fabricante());
        date_register_TextField.setText(stq.getDate_register().toString());
        descricao_TextArea.setText(stq.getDescricao());
        btGravar.setEnabled(false);
        btExcluir.setEnabled(true);
        btAlterar.setEnabled(true);
        habilitaCampText();
        
    }//GEN-LAST:event_tabelaEstoqueMouseClicked

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        
        Estoque stq = new Estoque();
        EstoqueDao stqDao = new EstoqueDao();
        
        int index = tabelaEstoque.getSelectedRow(); //retorna o numero da linha selecionada
        
        stq = stqDao.getEstoqueRegistro().get(index);
        
        switch(JOptionPane.showConfirmDialog(null, 
                "ALTERAÇÃO DE DADOS \n"+
                    stq.getNome()+"\n"+
                    stq.getModelo()+"\n"+
                    stq.getMarca()+"\n"+
                    stq.getSetor()+"\n"+
                    stq.getPosicao_prateleira()+"\n"+
                    stq.getQuant_atual()+"\n"+
                    stq.getQuant_min()+"\n"+
                    stq.getCod_fabricante()+"\n"+
                    stq.getDescricao()+"\n"+
                "SERÁ ALTERADO PARA \n"+
                    nome_TextField.getText()+"\n"+
                    modelo_TextField.getText()+"\n"+
                    marca_TextField.getText()+"\n"+
                    setor_TextField.getText()+"\n"+
                    posicao_prateleira_TextField.getText()+"\n"+
                    quant_atual_TextField.getText()+"\n"+
                    quant_min_TextField.getText()+"\n"+
                    cod_fabricante_TextField.getText()+"\n"+
                    descricao_TextArea.getText()+"\n"+
                "DESEJA REALMENTE ALTERAR OS CAMPOS ?"
                ,"Alteração de dados",JOptionPane.YES_NO_OPTION))
        {
            case 0:
                stq.setNome(nome_TextField.getText());
                stq.setModelo(modelo_TextField.getText());
                stq.setMarca(marca_TextField.getText());
                stq.setSetor(setor_TextField.getText());
                stq.setPosicao_prateleira(posicao_prateleira_TextField.getText());
                stq.setQuant_atual(Integer.parseInt(quant_atual_TextField.getText()));
                stq.setQuant_min(Integer.parseInt(quant_min_TextField.getText()));
                stq.setCod_fabricante(cod_fabricante_TextField.getText());
                stq.setDescricao(descricao_TextArea.getText());
                
                JOptionPane.showMessageDialog(null, "As informações foram atualizadas.","Sucesso",JOptionPane.INFORMATION_MESSAGE);
                stqDao.update(stq);
                limparTexto();
                btAlterar.setEnabled(false);
                
                break;
            
            case 1:
                JOptionPane.showMessageDialog(null, "Nenhuma alteração foi feita.","AVISO",JOptionPane.INFORMATION_MESSAGE);
                break;
        }
        try {
            carregarTabela();
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a tabela do banco "+error,"ERRO",HEIGHT);
        }
        
    }//GEN-LAST:event_btAlterarActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        // TODO add your handling code here:
        index = tabelaEstoque.getRowCount()-1;
        setarCampos(listar.getEstoqueRegistro().get(index));
    }//GEN-LAST:event_ultimoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        index--;
        if(index>=0)
            setarCampos(listar.getEstoqueRegistro().get(index));
        else
        {
            index = 0;
            setarCampos(listar.getEstoqueRegistro().get(index));
            JOptionPane.showMessageDialog(null, "Você já esta no primeiro registro","ALERTA",JOptionPane.WARNING_MESSAGE);    
        }
    }//GEN-LAST:event_voltarActionPerformed
    
    private void carregarTabela() throws Exception{
        DefaultTableModel modelo = (DefaultTableModel) tabelaEstoque.getModel();
        modelo.setNumRows(0);
            java.sql.Connection con = ConnectionFactory.createConnectionToMySQL();
            PreparedStatement pstm = null;
            ResultSet rset = null;
        try
        {
            pstm = con.prepareStatement("select * from estoqueregistro.estoque;");
            rset = pstm.executeQuery();
            
            while(rset.next())
            {
                modelo.addRow(new Object[]{
                    rset.getInt(1),
                    rset.getString(2),
                    rset.getString(3),
                    rset.getString(4),
                    rset.getString(5),
                    rset.getString(6),
                    rset.getInt(7),
                    rset.getInt(8),
                    rset.getString(9),
                    rset.getDate(10)
                });
            }
        }
	catch(Exception error) 
	{	
             JOptionPane.showMessageDialog(null, "Erro ao carregar a tabela do banco "+error,"ERRO",HEIGHT);
	}
        finally
	{	
            try 
            {
                if(rset != null) 
                {
                    rset.close();
                }
                if(pstm != null) 
                {
                    pstm.close();
                }
                if(con != null) 
                {
                    con.close();
                }
            }
            catch(Exception error) 
            {
                JOptionPane.showMessageDialog(null, "Erro ao encerrar conexão com o banco "+error,"ERRO",HEIGHT);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCadastro().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avancar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JLabel cod_fabricante_Label;
    private javax.swing.JTextField cod_fabricante_TextField;
    private javax.swing.JLabel date_register_Label;
    private javax.swing.JTextField date_register_TextField;
    private javax.swing.JLabel descricao_Label;
    private javax.swing.JTextArea descricao_TextArea;
    private javax.swing.JLabel foto_Label;
    private javax.swing.JLabel id_estoque_Label;
    private javax.swing.JTextField id_estoque_TextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel marca_Label;
    private javax.swing.JTextField marca_TextField;
    private javax.swing.JLabel modelo_Label;
    private javax.swing.JTextField modelo_TextField;
    private javax.swing.JLabel nome_Label;
    private javax.swing.JTextField nome_TextField;
    private javax.swing.JButton novo;
    private javax.swing.JLabel posicao_prateleira_Label;
    private javax.swing.JTextField posicao_prateleira_TextField;
    private javax.swing.JButton primeiro;
    private javax.swing.JLabel quant_atual_Label;
    private javax.swing.JTextField quant_atual_TextField;
    private javax.swing.JLabel quant_min_Label;
    private javax.swing.JTextField quant_min_TextField;
    private javax.swing.JLabel setor_Label;
    private javax.swing.JTextField setor_TextField;
    private javax.swing.JTable tabelaEstoque;
    private javax.swing.JButton ultimo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
