/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.estoque.telas;

import br.com.estoque.dao.EstoqueDao;
import br.com.estoque.factory.ConnectionFactory;
import br.com.estoque.model.Estoque;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author rafae
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() throws Exception {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome_Label = new javax.swing.JLabel();
        modelo_Label = new javax.swing.JLabel();
        foto_Label = new javax.swing.JLabel();
        descricao_Label = new javax.swing.JLabel();
        quant_atual_Label = new javax.swing.JLabel();
        cod_fabricante_Label = new javax.swing.JLabel();
        quant_min_Label = new javax.swing.JLabel();
        marca_Label = new javax.swing.JLabel();
        posicao_prateleira_Label = new javax.swing.JLabel();
        setor_Label = new javax.swing.JLabel();
        modelo_TextField = new javax.swing.JTextField();
        nome_TextField = new javax.swing.JTextField();
        marca_TextField = new javax.swing.JTextField();
        posicao_prateleira_TextField = new javax.swing.JTextField();
        setor_TextField = new javax.swing.JTextField();
        cod_fabricante_TextField = new javax.swing.JTextField();
        quant_min_TextField = new javax.swing.JTextField();
        quant_atual_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao_TextArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEstoque = new javax.swing.JTable();
        novo = new javax.swing.JButton();
        primeiro = new javax.swing.JButton();
        gravar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        avancar = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        id_estoque_Label = new javax.swing.JLabel();
        id_estoque_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calypto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de almoxarifado"));

        nome_Label.setText("Nome");

        modelo_Label.setText("Modelo");

        foto_Label.setText("Foto");

        descricao_Label.setText("Descrição");

        quant_atual_Label.setText("Quantidade atual");

        cod_fabricante_Label.setText("Código do fabricante");

        quant_min_Label.setText("Quantidade mínima");

        marca_Label.setText("Marca");

        posicao_prateleira_Label.setText("Prateleira");

        setor_Label.setText("Setor");

        nome_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_TextFieldActionPerformed(evt);
            }
        });

        posicao_prateleira_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicao_prateleira_TextFieldActionPerformed(evt);
            }
        });

        setor_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setor_TextFieldActionPerformed(evt);
            }
        });

        quant_min_TextField.setName(""); // NOI18N
        quant_min_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quant_min_TextFieldActionPerformed(evt);
            }
        });

        descricao_TextArea.setColumns(20);
        descricao_TextArea.setRows(5);
        jScrollPane1.setViewportView(descricao_TextArea);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "MODELO", "MARCA", "SETOR", "PRATELEIRA", "QUANTIDADE ATUAL", "QUANTIDADE MÍNIMA", "CÓDIGO DO FABRICANTE", "DATA DO REGISTRO"
            }
        ));
        jScrollPane2.setViewportView(tabelaEstoque);

        novo.setText("NOVO");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        primeiro.setText("PRIMEIRO");
        primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroActionPerformed(evt);
            }
        });

        gravar.setText("GRAVAR");
        gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarActionPerformed(evt);
            }
        });

        alterar.setText("ALTERAR");

        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        voltar.setText("VOLTAR");

        avancar.setText("AVANÇAR");
        avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarActionPerformed(evt);
            }
        });

        ultimo.setText("ÚLTIMO");

        id_estoque_Label.setText("ID");

        id_estoque_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_estoque_TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(posicao_prateleira_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicao_prateleira_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(marca_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                        .addComponent(nome_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(modelo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome_TextField)
                                    .addComponent(modelo_TextField)
                                    .addComponent(marca_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                        .addGap(88, 88, 88)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cod_fabricante_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quant_min_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(quant_atual_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quant_min_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(quant_atual_TextField)
                                    .addComponent(cod_fabricante_TextField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(setor_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(id_estoque_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(id_estoque_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 44, Short.MAX_VALUE))
                                    .addComponent(setor_TextField))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(descricao_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216)
                                .addComponent(foto_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(437, 437, 437))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alterar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(primeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ultimo)
                                .addGap(12, 12, 12)
                                .addComponent(avancar)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voltar)
                            .addComponent(excluir))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome_Label)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nome_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(modelo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(modelo_Label))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(marca_Label)
                                    .addComponent(marca_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(posicao_prateleira_Label)
                                    .addComponent(posicao_prateleira_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novo)
                            .addComponent(gravar)
                            .addComponent(alterar)
                            .addComponent(excluir)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cod_fabricante_Label)
                                    .addComponent(cod_fabricante_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descricao_Label)
                                    .addComponent(foto_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quant_min_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quant_min_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(quant_atual_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quant_atual_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(setor_Label)
                                    .addComponent(setor_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_estoque_Label)
                            .addComponent(id_estoque_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primeiro)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(voltar)
                        .addComponent(avancar)
                        .addComponent(ultimo)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setor_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setor_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setor_TextFieldActionPerformed

    private void posicao_prateleira_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicao_prateleira_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicao_prateleira_TextFieldActionPerformed

    private void nome_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_TextFieldActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoActionPerformed

    private void primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeiroActionPerformed

    private void avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avancarActionPerformed

    private void gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarActionPerformed
        // TODO add your handling code here:
        Estoque stq = new Estoque();
        EstoqueDao stqDao = new EstoqueDao();
        
        stq.setNome(nome_TextField.getText());
        stq.setModelo(modelo_TextField.getText());
        stq.setMarca(marca_TextField.getText());
        stq.setPosicao_prateleira(posicao_prateleira_TextField.getText());
        stq.setDescricao(descricao_TextArea.getText());
        stq.setCod_fabricante(cod_fabricante_TextField.getText());
        stq.setQuant_min(Integer.parseInt(quant_min_TextField.getText()));
        stq.setQuant_atual(Integer.parseInt(quant_atual_TextField.getText()));
        stq.setSetor(setor_TextField.getText());
        stq.setDescricao(descricao_TextArea.getText());
        stq.setDate_register(new Date());
        
        stqDao.save(stq);
    }//GEN-LAST:event_gravarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirActionPerformed

    private void id_estoque_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_estoque_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_estoque_TextFieldActionPerformed

    private void quant_min_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quant_min_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quant_min_TextFieldActionPerformed
    
    private void carregarTabela() throws Exception{
        DefaultTableModel modelo = (DefaultTableModel) tabelaEstoque.getModel();
        modelo.setNumRows(0);
            java.sql.Connection con = ConnectionFactory.createConnectionToMySQL();
            PreparedStatement pstm = null;
            ResultSet rset = null;
        try
        {
            pstm = con.prepareStatement("select * from estoqueregistro.estoque;");
            rset = pstm.executeQuery();
            
            while(rset.next())
            {
                modelo.addRow(new Object[]{
                    rset.getInt(1),
                    rset.getString(2),
                    rset.getString(3),
                    rset.getString(4),
                    rset.getString(5),
                    rset.getString(6),
                    rset.getInt(7),
                    rset.getInt(8),
                    rset.getString(9),
                    rset.getDate(10)
                });
            }
        }
	catch(Exception error) 
	{	
             JOptionPane.showMessageDialog(null, "Erro ao carregar a tabela do banco "+error,"ERRO",HEIGHT);
	}
        finally
	{	
            try 
            {
                if(rset != null) 
                {
                    rset.close();
                }
                if(pstm != null) 
                {
                    pstm.close();
                }
                if(con != null) 
                {
                    con.close();
                }
            }
            catch(Exception error) 
            {
                JOptionPane.showMessageDialog(null, "Erro ao encerrar conexão com o banco "+error,"ERRO",HEIGHT);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCadastro().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton avancar;
    private javax.swing.JLabel cod_fabricante_Label;
    private javax.swing.JTextField cod_fabricante_TextField;
    private javax.swing.JLabel descricao_Label;
    private javax.swing.JTextArea descricao_TextArea;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel foto_Label;
    private javax.swing.JButton gravar;
    private javax.swing.JLabel id_estoque_Label;
    private javax.swing.JTextField id_estoque_TextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel marca_Label;
    private javax.swing.JTextField marca_TextField;
    private javax.swing.JLabel modelo_Label;
    private javax.swing.JTextField modelo_TextField;
    private javax.swing.JLabel nome_Label;
    private javax.swing.JTextField nome_TextField;
    private javax.swing.JButton novo;
    private javax.swing.JLabel posicao_prateleira_Label;
    private javax.swing.JTextField posicao_prateleira_TextField;
    private javax.swing.JButton primeiro;
    private javax.swing.JLabel quant_atual_Label;
    private javax.swing.JTextField quant_atual_TextField;
    private javax.swing.JLabel quant_min_Label;
    private javax.swing.JTextField quant_min_TextField;
    private javax.swing.JLabel setor_Label;
    private javax.swing.JTextField setor_TextField;
    private javax.swing.JTable tabelaEstoque;
    private javax.swing.JButton ultimo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
